### ISSUE TITLE
break crafts

### ISSUE THREAD

**Issue by InterVi** [NathanSalapat/more_fire#11]
![_2017-07-05_20-06-18](https://user-images.githubusercontent.com/16702343/27881975-7bee41f4-61d3-11e7-86ad-9337927af9e4.png)
and wood helmet

**Comment by NathanSalapat** [comment]
I'll try and get a fix. I'm currently using shapeless recipes, but I can change that. I need to update the fire functions too, though that isn't related to this.

**Comment by InterVi** [comment]
need to provide my list of mods?

**Comment by NathanSalapat** [comment]
I just changed the recipe it's now:
K   K
KWK

where K is group:kindling, and W is group:wood. I also fixed the kindling node while I was at it so it can be placed.

**Comment by InterVi** [comment]
working, thanks
